# -*- coding: utf-8 -*-
"""
/***************************************************************************
 v5PFES
                                 A QGIS plugin
 Support build PFES Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-06
        git sha              : $Format:%H$
        copyright            : (C) 2022 by IFFEE
        email                : phamquangduongvfu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .main_dialog import v5PFESDialog
import os.path



class v5PFES_menu:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.v5PFES_menu = None

    def add_submenu(self, submenu):
        if self.v5PFES_menu != None:
            self.v5PFES_menu.addMenu(submenu)
        else:
            self.iface.addPluginToMenu("&v5PFES", submenu.menuAction())

    def initGui(self):
        # Uncomment the following two lines to have hcmgis accessible from a top-level menu
        self.v5PFES_menu = QMenu(QCoreApplication.translate("v5pfes", "v5PFES"))
        self.iface.mainWindow().menuBar().insertMenu(self.iface.firstRightStandardMenu().menuAction(), self.v5PFES_menu)
        # Tai ban bo DBR tu FORMIS
        self.download_DBR_menu = QMenu(u'Download FRMS')		
        self.add_submenu(self.download_DBR_menu)

        #Xay dung ban do DVMTR
        self.build_PFESMap_menu = QMenu(u'Build Map')		
        self.add_submenu(self.build_PFESMap_menu)

        self.static_form_menu = QMenu(u'Statistic')		
        self.add_submenu(self.static_form_menu)

        self.tool_menu = QMenu(u'Tool')		
        self.add_submenu(self.tool_menu)

        self.help_menu = QMenu(u'Help')		
        self.add_submenu(self.help_menu)
    def unload(self):
         self.iface.mainWindow().menuBar().removeAction(self.v5PFES_menu.menuAction())

